# numpy

In [13]:
#coding:utf-8
import numpy as np

## ndarray

### 轴和维数

In [14]:
vector = np.array([1,2,3,4])
print u"向量", vector
print u"维数：",vector.ndim

向量 [1 2 3 4]
维数： 1


In [15]:
matrix = np.array([[1,2,5],[3,3,4],[9,4,5]])
print u"矩阵:"
print matrix
print u"维数：",matrix.ndim
print "竖为0轴，横为1轴：", matrix.sum(axis=0), matrix.sum(axis=1)

矩阵:
[[1 2 5]
 [3 3 4]
 [9 4 5]]
维数： 2
竖为0轴，横为1轴： [13  9 14] [ 8 10 18]


ndarray的维数和向量等维数不同，ndarray的维数表示数据的存储格式（一维数组，二位数组，三维数组）

### 引用及数据更改

In [16]:
secondcol = matrix[:,1]
secondcol[1] = 6
print secondcol
print matrix
secondcol = matrix[:,1:2]
secondcol[1][0] = 4
print secondcol
print matrix

[2 6 4]
[[1 2 5]
 [3 6 4]
 [9 4 5]]
[[2]
 [4]
 [4]]
[[1 2 5]
 [3 4 4]
 [9 4 5]]


原矩阵被更改，secondcol是指向第二列的引用

In [17]:
subma = matrix[:,1:]
subma[1][1] = 7
print subma
print matrix

[[2 5]
 [4 7]
 [4 5]]
[[1 2 5]
 [3 4 7]
 [9 4 5]]


原矩阵被更改，subma是指向部分矩阵的引用

In [18]:
secondcol = matrix[:,[1]]
secondcol[1] = -1
print secondcol
print matrix

[[ 2]
 [-1]
 [ 4]]
[[1 2 5]
 [3 4 7]
 [9 4 5]]


原矩阵没有被更改，secondcol是新的列向量

In [22]:
subma = matrix[:,1:]
newma = np.empty((3,2))
newma[:,:] = subma #这两步操作可以用 newma = np.asarray(subma)代替
newma[1][1] = 3
print subma
print newma
print matrix

[[2 5]
 [4 7]
 [4 5]]
[[ 2.  5.]
 [ 4.  3.]
 [ 4.  5.]]
[[1 2 5]
 [3 4 7]
 [9 4 5]]


原矩阵没有被更改，newma是新的矩阵，subma是引用。